# Generated by Django 3.2.7 on 2023-07-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_code', models.CharField(max_length=100)),
                ('student', models.CharField(choices=[], max_length=100)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
